### ISSUE TITLE
Usage help 

### ISSUE THREAD

**Issue by hmyh1202** [noush-joglekar/scisorseqr#1]
hello：

 How use this package to identify splice event from long pacbio reads. 
Some help or wiki could be added in this page.
Than you !

**Comment by noush-joglekar** [comment]
Hey! If you install the package with the following command it should allow you to see the vignette
devtools::install_github('noush-joglekar/scisorseqr', build_vignettes = TRUE)
browseVignettes('scisorseqr')

I'm still working on adding details but the HTML document walks you through usage of the different functions. For identifying splice-sites and getting intron chains from PacBio data you need the STARalign() command followed by the MapAndFilter() function. It should output a directory called LRProcessingOutput which contains GFF files for the consensus splice sites. Let me know if you face issues running those two commands!
