### ISSUE TITLE
cannot download this package

### ISSUE THREAD

**Issue by yuanwsy** [noush-joglekar/scisorseqr#12]
when I download the package ,I met a problem like this ,and canno solve it:

E  creating vignettes (10.1s)
   --- re-building ‘scisorseqr-StandardWorkflow.Rmd’ using rmarkdown
   ! LaTeX Error: File `iftex.sty' not found.

   ! Emergency stop.
   <read *>

   Error: processing vignette 'scisorseqr-StandardWorkflow.Rmd' failed with diagnostics:
   LaTeX failed to compile /tmp/Rtmp95bjzT/Rbuild3cd1a6e193b28/scisorseqr/vignettes/scisorseqr-StandardWorkflow.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See scisorseqr-StandardWorkflow.log for more info.
   --- failed re-building ‘scisorseqr-StandardWorkflow.Rmd’

   SUMMARY: processing the following file failed:
     ‘scisorseqr-StandardWorkflow.Rmd’

   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'scisorseqr' from GitHub:
  ! System command 'R' failed

do you know something about this situation?

**Comment by noush-joglekar** [comment]
Hi there! Could you try downloading without building the vignette? It seems like an issue with markdown rendering
