### ISSUE TITLE
Segmentation fault: v1.0b.getGenes_andHighlightProblematicReadsAndGenes.awk

### ISSUE THREAD

**Issue by legbar** [noush-joglekar/scisorseqr#2]
When the [v1.0b.getGenes_andHighlightProblematicReadsAndGenes.awk](https://github.com/noush-joglekar/scisorseqr/blob/master/inst/bash/v1.0b.getGenes_andHighlightProblematicReadsAndGenes.awk) script is called from [mapAndAlignReads.sh](https://github.com/peterkilfeather/scisorseqr/blob/master/inst/bash/mapAndAlignReads.sh), the first block of code (announced by `## A. parsing file2="name-of-my-intron-gff-file"` section of code produces a segmentation fault that terminates the awk script. 

As a result, the `mapping.bestperRead.RNAdirection.withConsensIntrons.transcriptWise.genes.gz` file which I believe it is supposed to populate is empty.

I am using ONT reads mapped using minimap2 with the same parameters specified in [minimap2comm.sh](https://github.com/noush-joglekar/scisorseqr/blob/master/inst/bash/minimap2comm.sh). Reads were mapped to Gencode vM25 primary assembly and I am using the Gencode vM25 GTF annotation. I am using the scripts directly, because I am handling bulk RNASeq data.

**Comment by peterkilfeather** [comment]
If I split the mapping gff and sortedAnno by chromosome and then split the per-chromosome mapping file into 100,000 read chunks, it completes successfully.

**Comment by noush-joglekar** [comment]
Ah interesting, I've never personally run into an issue while executing that particular chunk of the code, but glad you managed to figure it out! The higher throughput of the bulk data may be a limiting factor, I'll keep that in mind. Thanks!

**Comment by peterkilfeather** [comment]
In actual fact I found the issue and it was with my own machine: I was running mawk as my default awk interpreter. As soon as I installed gawk, the entire script ran perfectly without needing to split any intermediate files.

**Comment by noush-joglekar** [comment]
Oh that's great to hear! Good catch, may be useful to future users :)

**Comment by kwglam** [comment]
> When the [v1.0b.getGenes_andHighlightProblematicReadsAndGenes.awk](https://github.com/noush-joglekar/scisorseqr/blob/master/inst/bash/v1.0b.getGenes_andHighlightProblematicReadsAndGenes.awk) script is called from [mapAndAlignReads.sh](https://github.com/peterkilfeather/scisorseqr/blob/master/inst/bash/mapAndAlignReads.sh), the first block of code (announced by `## A. parsing file2="name-of-my-intron-gff-file"` section of code produces a segmentation fault that terminates the awk script.
> 
> As a result, the `mapping.bestperRead.RNAdirection.withConsensIntrons.transcriptWise.genes.gz` file which I believe it is supposed to populate is empty.
> 
> I am using ONT reads mapped using minimap2 with the same parameters specified in [minimap2comm.sh](https://github.com/noush-joglekar/scisorseqr/blob/master/inst/bash/minimap2comm.sh). Reads were mapped to Gencode vM25 primary assembly and I am using the Gencode vM25 GTF annotation. I am using the scripts directly, because I am handling bulk RNASeq data.

**Comment by kwglam** [comment]
> When the [v1.0b.getGenes_andHighlightProblematicReadsAndGenes.awk](https://github.com/noush-joglekar/scisorseqr/blob/master/inst/bash/v1.0b.getGenes_andHighlightProblematicReadsAndGenes.awk) script is called from [mapAndAlignReads.sh](https://github.com/peterkilfeather/scisorseqr/blob/master/inst/bash/mapAndAlignReads.sh), the first block of code (announced by `## A. parsing file2="name-of-my-intron-gff-file"` section of code produces a segmentation fault that terminates the awk script.
> 
> As a result, the `mapping.bestperRead.RNAdirection.withConsensIntrons.transcriptWise.genes.gz` file which I believe it is supposed to populate is empty.
> 
> I am using ONT reads mapped using minimap2 with the same parameters specified in [minimap2comm.sh](https://github.com/noush-joglekar/scisorseqr/blob/master/inst/bash/minimap2comm.sh). Reads were mapped to Gencode vM25 primary assembly and I am using the Gencode vM25 GTF annotation. I am using the scripts directly, because I am handling bulk RNASeq data.

Hi,

I believe I am encountering the same issue here. When running "MapAndFilter", I have got a bunch of files generated in the LRProcessingOutput folder (see below). However, the file "mapping.bestperRead.RNAdirection.withConsensIntrons.transcriptWise.genes.gz" has been emptied for quite a while (more than 12 hours) and the program is kind of stuck at the code 'awk -v sortedAnno=tmpDir/sortedAnno'. Any insights how to solve it? Thanks!

Files in folder "LRProcessingOutput":
mapping.bestperRead.RNAdirection.withConsensIntrons.transcriptWise.genes.gz
mapping.bestperRead.RNAdirection.withConsensIntrons.introns.gff
mapping.bestperRead.RNAdirection.withConsensIntrons.bam
mapping.bestperRead.RNAdirection.withConsensIntrons.gff.gz
mapping.bestperRead.RNAdirection.withWeirdIntron.gff
mapping.bestperRead.RNAdirection.introns.type.gff.gz
parallel.comp.anno.guide.3.siteSeq
mapping.bestperRead.noRiboRNA.gff
mapping.bestperRead.noRiboRNA.introns.gff
mapping.bestperRead.noRiboRNA.bam

The code that I am running:
MapAndFilter(outputDir='./LRProcessingOutput', annoGZ='./gencode/gtf_files/mouse/gencode.vM23.primary_assembly.annotation.gtf.gz', numThreads=50, seqDir = './gencode/fa_files/mouse/GRCm38_by_chr/', filterFullLength=TRUE, cageBed = './CAGE_peaks/mm10_fair+new_CAGE_peaks_phase1and2.bed.gz', polyABed = './PolyAsites/atlas.clusters.2.0.GRCm38.96.wChr.bed.gz', cp_distance=50, genomeVersion="mm10")

**Comment by noush-joglekar** [comment]
Hey, the command to run looks correct so I'm assuming it's a formatting difference somewhere that the script is not equipped to deal with. Could you call a head on these two files: "mapping.bestperRead.RNAdirection.withWeirdIntron.gff" and "mapping.bestperRead.RNAdirection.withConsensIntrons.introns.gff"? Maybe that has a clue somewhere

**Comment by kwglam** [comment]
Hi Anoushka,
Thanks for the prompt reply. Here is info:

head  mapping.bestperRead.RNAdirection.withWeirdIntron.gff
chr13	mm10	cDNA_match	45711020	45711643	.	-	.	read_id "a414ac14-529f-4af7-96e1-f5629c2617e1.path1";
chr13	mm10	cDNA_match	45711881	45712146	.	-	.	read_id "a414ac14-529f-4af7-96e1-f5629c2617e1.path1";
chr17	mm10	cDNA_match	33996024	33996482	.	-	.	read_id "ee75c0b2-0e20-4987-9105-b5aee352b6d7.path1";
chr17	mm10	cDNA_match	33997328	33997560	.	-	.	read_id "ee75c0b2-0e20-4987-9105-b5aee352b6d7.path1";
chr17	mm10	cDNA_match	33999271	33999546	.	-	.	read_id "ee75c0b2-0e20-4987-9105-b5aee352b6d7.path1";

head mapping.bestperRead.RNAdirection.withConsensIntrons.introns.gff
chr7	mm10	intron	103826794	103827447	.	-	.	transcript_id_with_chr=11369ea4-2c02-49f8-a243-ac9a93383df3.path1@chr7
chr7	mm10	intron	103827671	103827783	.	-	.	transcript_id_with_chr=11369ea4-2c02-49f8-a243-ac9a93383df3.path1@chr7
chr7	mm10	intron	99839884	99844699	.	-	.	transcript_id_with_chr=e87ffc9d-67e7-4e43-9286-1fc3474221b3.path1@chr7
chr7	mm10	intron	99844835	99848298	.	-	.	transcript_id_with_chr=e87ffc9d-67e7-4e43-9286-1fc3474221b3.path1@chr7
chr7	mm10	intron	99848460	99848975	.	-	.	transcript_id_with_chr=e87ffc9d-67e7-4e43-9286-1fc3474221b3.path1@chr7
chr7	mm10	intron	99849060	99858763	.	-	.	transcript_id_with_chr=e87ffc9d-67e7-4e43-9286-1fc3474221b3.path1@chr7
chr15	mm10	intron	83563645	83571384	.	+	.	transcript_id_with_chr=edce80ee-39b0-44cc-9ccf-85297d59043e.path1@chr15

Thanks!!!

**Comment by noush-joglekar** [comment]
Hey there, sorry for the extreme delay in getting back to you. Did this get resolved on your end? Otherwise can you email me a subset of your data so I can troubleshoot on my end. It could be some kind of sorting issue, or a versioning thing

**Comment by nehagupta1215** [comment]
Hey Anoushka, 
 It seems like I am getting a similar error saying `LRProcessingOutput/mapping.bestperRead.RNAdirection.withConsensIntrons.gff.gz: No such file or directory`

I am trying to get my hand dirty on this tool therefore using the template data files already provided with the package. The command I am using goes like:

```
MapAndFilter( outputDir = "LRProcessingOutput",annoGZ = "genome/gencode.vM21.annotation.gtf.gz", numThreads = 24,
seqDir  = "all_chr_fastafile", genomeVersion = "mm10", cp_distance = 50)
```
I have gawk installed and using as my default interpreter as suggested in the above thread. 
Below are the list of files generated in the LRProcessingOutput directory:

```
mapping.bestperRead.bam
mapping.bestperRead.noRiboRNA.bam
mapping.bestperRead.noRiboRNA.gff.gz
mapping.bestperRead.noRiboRNA.introns.gff.gz
mapping.bestperRead.RNAdirection.introns.type.gff.gz
mapping.bestperRead.RNAdirection.withConsensIntrons.bam
mapping.bestperRead.RNAdirection.withConsensIntrons.introns.gff.gz
mapping.bestperRead.RNAdirection.withConsensIntrons.transcriptWise.genes.gz
mapping.bestperRead.RNAdirection.withWeirdIntron.gff.gz
newIsoforms_vs_Anno_ignoreAnno
parallel.comp.anno.guide.3.siteSeq
```

I also see broken pipe errors for the FastaToTbl function in the console. 

```
commandFile=LRProcessingOutput/parallel.comp.anno.guide.3.siteSeq
n=24
## 1. reading organizational data
## 2. execution
sh: 1: source: not found
sh: 1: FastaToTbl: not found
gzip: stdout: Broken pipe
sh: 1: FastaToTbl: not found
sh: 1: FastaToTbl: not found
```
`head mapping.bestperRead.RNAdirection.withWeirdIntron.gff ` for me looks similar structured as in the above thread but `head mapping.bestperRead.RNAdirection.withConsensIntrons.introns.gff` is empty.  I tried reinstalling the package and running with all the updated dependencies. 

Could you please let me know what could be the possible issue here? 
Thanks.

**Comment by noush-joglekar** [comment]
Hi Neha, since it's failing at the FastaToTbl step I believe there's something wrong with the path re-direction. It shouldn't have any issues locating the function so I'm a bit at a loss as to why this may be happening. What system are you running this on?

**Comment by nehagupta1215** [comment]
Hi Anoushka, 
I am running on Ubuntu 22.04.2 LTS and it looked like a system error. My  system wasn't recognizing file paths provided by the .sh file . It needed a '.' instead of 'source' when calling the f2t.sh file for each chromosome. I was able to fix this by adding couple of lines in the `main()` function of the v0.2.executeInParallel.py file. 
```
print("## 1. reading organizational data")
   commandList = []
   f = open(option.commandFile, 'r')
   for line in f:
       line = line.replace("source", "'.")
       line  = "bash -c " + line + "'"
       commandList.append(line.rstrip())

   print("## 2. execution")
   runcommands(commandList,"F",option.n)
```
Thanks
-Neha

**Comment by noush-joglekar** [comment]
Awesome, thanks!
