### ISSUE TITLE
Processed data matrix

### ISSUE THREAD

**Issue by gonzalobenegas** [noush-joglekar/scisorseqr#3]
Hello,

Would it be possible to get access to an already processed cell-by-isoform count matrix? I see a 10X cell-by-gene matrix in GEO, but not for long-read isoforms. This would greatly facilitate exploration of the data.

Thanks in advance,
Gonzalo

**Comment by noush-joglekar** [comment]
Hey Gonzalo! Would you mind dropping me an email (anj2026@med.cornell.edu) and I can send over the files and explain the format I used

**Comment by gonzalobenegas** [comment]
Just sent you an email, thanks!

**Comment by ChuanXu1** [comment]
@noush-joglekar, thanks for this resource. I would like to have the cell-by-gene matrix and accompanying cell type information. Would you mind also sending over the files to me (cx1@sanger.ac.uk)? Thank you in advance!
