### ISSUE TITLE
Struggling at Step 3 of vignette

### ISSUE THREAD

**Issue by calhoujd** [noush-joglekar/scisorseqr#7]
Hi,

I am getting close to making it through the full pipeline, but I have gotten stuck at Step 3 from the vignette (using the real data from the paper, specifically HIPP_replicate_1). I believe my problem is occuring at this section of mapAndAlignReads.sh:

time awk -v bestMatchFile=$outdir"/mapping.bestperRead.noRiboRNA.gff" \
-v intronTypeFile=$outdir"/mapping.bestperRead.RNAdirection.introns.type.gff.gz" \
-v outputCorrectFile=$outdir"/mapping.bestperRead.RNAdirection.withConsensIntrons.gff" \
-v outputUnClassifiableFile=$outdir"/mapping.bestperRead.RNAdirection.withWeirdIntron.gff" \
-f $scriptDir/v1.0b.correct.strand.bySpliceSiteConsensus.awk

I am getting the ...WeirdIntron file but not the ...withConsensIntrons file. Which causes the rest of the script to fail. Any thoughts? I've run this a few times and I'm not sure what else to try. I used the minimap for step 2 and that seemed to work fine. The first few steps of step 3 seem to run fine as well. 

If it helps, here is my script:

MapAndFilter(annoGZ = '/projects/b1073/WGS_peds_epilepsies/jdc_sandbox/scisorseq/Seurat/gencode.vM23.annotation.gtf.gz',
             numThreads=24,
             seqDir = '/projects/b1073/pipelines/commonref/Mus_musculus/UCSC/mm10/Sequence/Chromosomes/',
             filterFullLength=TRUE,
             cageBed = '/projects/b1073/WGS_peds_epilepsies/jdc_sandbox/scisorseq/Seurat/mm10_fair+new_CAGE_peaks_phase1and2.bed.gz',
             polyABed = '/projects/b1073/WGS_peds_epilepsies/jdc_sandbox/scisorseq/Seurat/atlas.clusters.2.0.GRCm38.96wchr.bed.gz',
             cp_distance=50)

Thanks,

Jeff

**Comment by noush-joglekar** [comment]
Hi Jeff, 

Based on the arguments it seems like this should work and nothing obvious seems to jump out. How many reads are you getting in the WeirdIntron file? For some reason it may be that all detected splice sites are being classified as non-consensus. Would it be possible for you to share (over [email](mailto:anj2026@med.cornell.edu)) all the input files you used for this function? I can try and run things step by step on my end and see where things are breaking down.

**Comment by calhoujd** [comment]
Hi Anoushka,

I emailed you and provided files via Box. I'm also re-running on the smaller sample data (TestHipp.fastq.gz). Our HPC appears to be busy today so not sure when the job will run. But when it does, I'll upload all of that as well in case the smaller files are easier for troubleshooting. Thanks again for your help figuring this out!

Take care,

Jeff

**Comment by calhoujd** [comment]
The issue appears to be entirely user error on my part. For the MapAndFilter step 3, I was pointing to a directory that had unzipped chrN.fa. I re-ran with gzipped chrN.fa.gz and it seems to have worked beautifully. :)
